name: jinlin_app
description: "鲸灵提醒 (CetaMind) - 智能提醒应用."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 添加 localization 支持
    sdk: flutter
  lunar: ^1.3.22 # 或者查看 pub.dev 获取最新版本号

  cupertino_icons: ^1.0.6
  http: ^1.2.1 # 用于网络请求
  shared_preferences: ^2.2.3 # 用于本地存储
  speech_to_text: ^6.6.1 # 用于语音转文字
  permission_handler: ^11.3.1 # 用于处理权限请求
  flutter_dotenv: ^5.1.0 # 用于加载 .env 文件中的环境变量
  uuid: ^4.4.0 # 用于生成唯一ID
  intl: ^0.19.0 # 用于国际化和格式化
  collection: ^1.18.0 # 用于集合操作
  logging: ^1.2.0 # 用于日志记录
  dio: ^5.4.1 # 用于网络请求
  record: ^5.0.4 # 用于录音
  path_provider: ^2.1.2 # 用于获取路径
  file_picker: ^6.1.1 # 用于文件选择
  share_plus: ^7.2.2 # 用于分享
  sqflite: ^2.3.2 # 用于SQLite数据库
  sqflite_common_ffi: ^2.3.2+1 # 用于在非移动平台上使用SQLite
  sqflite_common_ffi_web: ^0.4.2+3 # 用于在Web平台上使用SQLite
  path: ^1.9.0 # 用于处理路径
  hive: ^2.2.3 # 用于跨平台数据库
  hive_flutter: ^1.1.0 # Hive的Flutter扩展
  hive_generator: ^2.0.1 # 用于Hive模型生成

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15 # 用于代码生成

flutter:
  uses-material-design: true
  generate: true # 启用 intl 代码生成

  # --- 这里是重要的修改 ---
  # 声明需要包含的资源文件
  assets:
    - .env # 告诉 Flutter 把项目根目录下的 .env 文件作为资源包含进来
  # --- 修改结束 ---


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # 如果你之前有 assets 区块，请确保 .env 那一行被包含在里面，像这样:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #   - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages